<?php
/**
 * @brief	Liste des contrôles de chaque candidats ayant passés l'épreuve
 *
 * Vue principale de visualisation de l'ensemble des contrôles d'une épreuve QCM.
 * User: durandcedric
 * Date: 25/09/16
 * Time: 11:43
 *
 * Copyright (c) 2015-2017 Cédric DURAND (durandcedric@avitheque.net)
 * Dual licensed under the MIT (http://www.opensource.org/licenses/mit-license.php)
 * and GPL (http://www.opensource.org/licenses/gpl-license.php) licenses.
 */

// Récupération de l'instance du singleton InstanceStorage permettant de gérer les échanges avec le contrôleur
$oInstanceStorage	= InstanceStorage::getInstance();

// Présentation d'un article
$sArticle = "<h2>Liste des contrôles pour l'épreuve sélectionnée</h2>";


//#################################################################################################

// Ajout de l'article à VIEW_MAIN
ViewRender::addToMain($sArticle);

// Rendu final de la vue
ViewRender::render();