<?php
/**
 * @brief	Liste des épreuves à corriger
 *
 * Vue principale de correction des épreuves QCM.
 * User: durandcedric
 * Date: 25/09/16
 * Time: 11:43
 *
 * Copyright (c) 2015-2017 Cédric DURAND (durandcedric@avitheque.net)
 * Dual licensed under the MIT (http://www.opensource.org/licenses/mit-license.php)
 * and GPL (http://www.opensource.org/licenses/gpl-license.php) licenses.
 */

// Récupération de l'instance du singleton InstanceStorage permettant de gérer les échanges avec le contrôleur
$oInstanceStorage	= InstanceStorage::getInstance();

// Initialisation d'un système d'onglets
$sArticle			= "<section class=\"tabs\">
						<ul>
							<li><a href=\"#tabs-epreuve\">Programmation</a></li>
							<li><a href=\"#tabs-correction\">Correction</a></li>
						</ul>";

//=================================================================================================
// PROGRAMMATION DES EPREUVES
//=================================================================================================
$sArticle			.= "<div id=\"tabs-epreuve\">";

// Titre de la liste des épreuves
$sArticle			.=  "<h2>Liste des épreuves programmées</h2>
						<p>
						</p>";

// Récupération de la liste des épreuves QCM
$aListeEpreuveQCM	= $oInstanceStorage->getData('liste_epreuve');

// Construction du tableau récapitulatif des formulaires
$oEpreuve = new DatatableHelper("table-epreuve",		$aListeEpreuveQCM);
$oEpreuve->setClassColumn("align-left strong",			"titre_formulaire");
$oEpreuve->setClassColumn("strong",						"libelle_groupe");

// Formatage du champ DATE
$oEpreuve->setFormatOnColumn('datetime_epreuve',		DataHelper::DATA_TYPE_DATETIME);

// Personnalisation des noms de colonne
$aColonnes = array(
	'datetime_epreuve'				=> "DATE DE PROGRAMMATION",
	'libelle_groupe'				=> "GROUPE",
	'libelle_stage'					=> "STAGE",
	'titre_formulaire'				=> "ÉPREUVE",
	'duree_epreuve'					=> "DURÉE (min)"
);
$oEpreuve->renameColumns($aColonnes, true);

// Fonctionnalité réalisée en MODE_NOMINAL
if (!defined('MODE_DEBUG') || !(bool) MODE_DEBUG) {
	// Masque les épreuves qui ne sont pas accessibles au candidat
	$oEpreuve->setConditionalClassOnColumn('debut_epreuve',	'>', 'maintenant', "strong grey",	$aColonnes);
	$oEpreuve->setConditionalClassOnColumn('fin_epreuve',	'<', 'maintenant', "strong grey",	$aColonnes);
	$oEpreuve->setConditionalClassOnColumn('debut_epreuve',	'>', 'maintenant', "disabled",		"ACTION");
	$oEpreuve->setConditionalClassOnColumn('fin_epreuve',	'<', 'maintenant', "disabled",		"ACTION");
}

// Ajout d'une colonne [ACTION] avec un lien HREF permettant au candidat de participer si le fomulaire est valide
$oEpreuve->setConditionalTextOnColumn("ACTION", "validation_formulaire", 1,"En attente...", "strong");
$oEpreuve->setConditionalAnchorOnColumn("ACTION", "modifiable_controle", 1,"id_epreuve", "Continuer", "/epreuve?id_epreuve=", "green tooltip-track", "Continuer l'épreuve QCM");
$oEpreuve->setConditionalAnchorOnColumn("ACTION", "validation_formulaire", 2,"id_epreuve", "Lancer", "/epreuve?id_epreuve=", "green tooltip-track", "Passer l'épreuve QCM");

// Ajout du rendu HTML du tableau à l'article
$sArticle			.= $oEpreuve->renderHTML();

// Finalisationde l'onglet
$sArticle			.= "</div>";


//=================================================================================================
// CORRECTION DES EPREUVES
//=================================================================================================
$sArticle			.= "<div id=\"tabs-correction\">";

// Titre de la liste des épreuves corrigées
$sArticle			.=  "<h2>Liste des épreuves corrigées</h2>
						<p>
						</p>";

// Récupération de la liste des épreuves QCM corrigées
$aListeCorrectionQCM = $oInstanceStorage->getData('liste_correction');

// Construction du tableau récapitulatif des formulaires
$oCorrection = new DatatableHelper("table-correction",	$aListeCorrectionQCM);
$oCorrection->setClassColumn("align-left strong",		"titre_formulaire");
$oCorrection->setClassColumn("strong",					"libelle_groupe");

// Formatage du champ DATE
$oCorrection->setFormatOnColumn('datetime_epreuve',		DataHelper::DATA_TYPE_DATETIME);

// Personnalisation des noms de colonne
$aColonnes = array(
	'datetime_epreuve'				=> "DATE DE PROGRAMMATION",
	'libelle_groupe'				=> "GROUPE",
	'libelle_stage'					=> "STAGE",
	'titre_formulaire'				=> "ÉPREUVE",
	'duree_epreuve'					=> "DURÉE (min)"
);
$oCorrection->renameColumns($aColonnes, true);

// Ajout du rendu HTML du tableau à l'article
$sArticle			.= $oCorrection->renderHTML();

// Finalisation de l'onglet
$sArticle			.= "</div>";

//#################################################################################################

// Ajout de l'article à VIEW_MAIN
ViewRender::addToMain($sArticle);

// Rendu final de la vue
ViewRender::render();
