<?php
/**
 * @brief	Programmation d'une épreuve.
 *
 * Vue permettant d'éditer les paramètres de programmation d'une épreuve.
 * User: durandcedric
 * Date: 25/09/16
 * Time: 11:43
 *
 * Copyright (c) 2015-2017 Cédric DURAND (durandcedric@avitheque.net)
 * Dual licensed under the MIT (http://www.opensource.org/licenses/mit-license.php)
 * and GPL (http://www.opensource.org/licenses/gpl-license.php) licenses.
 */

//#################################################################################################
// INTERFACE DE CRÉATION DU FORMULAIRE
//#################################################################################################

// Initialisation du formulaire
ViewRender::addToFormStart("<form action=\"#\" method=\"post\" name=\"generation\">");

// Construction du formulaire QCM
$oFormulaire = new GenerationHelper(false, false);

// Création de l'entête du formulaire
$sArticle = "<h2>
				Programmation d'une épreuve
				" . $oFormulaire->getCorrectionButton() . "
			</h2>
			<p>
				Cette interface permet de configurer une épreuve.
			</p>";
// Ajout du contenu au VIEW_MAIN
ViewRender::addToMain($sArticle);

// Zone du QCM injecté dans $_SESSION[VIEW_MAIN]
ViewRender::addToMain($oFormulaire->render());


//#################################################################################################
// VALIDATION DU FORMULAIRE
//#################################################################################################

// Création des boutons du formulaire
$oGroupButton = new GroupButtonFormulaireHelper(false, true);
// Ajout du groupe de boutons au VIEW_FOOTER
ViewRender::addToFooter($oGroupButton->render());

// Rendu final de la vue
ViewRender::render();
