<?php
/**
 * @brief	Édition
 *
 * Vue de création du formulaire QCM.
 *
 * @li Dans les tableaux, les clés de questions et de réponses commencent à la valeur [1].
 * User: durandcedric
 * Date: 25/09/16
 * Time: 11:43
 *
 * Copyright (c) 2015-2017 Cédric DURAND (durandcedric@avitheque.net)
 * Dual licensed under the MIT (http://www.opensource.org/licenses/mit-license.php)
 * and GPL (http://www.opensource.org/licenses/gpl-license.php) licenses.
 */

//#################################################################################################
// INTERFACE DE CRÉATION DU QUESTIONNAIRE
//#################################################################################################

// Initialisation du formulaire
ViewRender::addToFormStart("<form action=\"#\" method=\"post\" name=\"generation\">");

// Construction du formulaire QCM
$oFormulaire = new FormulaireHelper(true, false, false, true);

// Création de l'entête du formulaire
$sArticle = "<h2>
				Génération d'un formulaire QCM
				" . $oFormulaire->getCorrectionButton() . "
			</h2>
			<p>
				Cette interface permet de configurer la génération du formulaire QCM au format AMC.
			</p>";
// Ajout du contenu au VIEW_MAIN
ViewRender::addToMain($sArticle);

// Zone du QCM injecté dans $_SESSION[VIEW_MAIN]
ViewRender::addToMain($oFormulaire->render());


//#################################################################################################
// VALIDATION DU FORMULAIRE
//#################################################################################################

// Création des boutons du formulaire
$oGroupButton = new GroupButtonFormulaireHelper(false, true);
// Ajout du groupe de boutons au VIEW_FOOTER
ViewRender::addToFooter($oGroupButton->render());

// Rendu final de la vue
ViewRender::render();
