<?php
/**
 * @brief	Documentation destinée au(x) développeur(s).
 *
 * Vue principale de développement de l'application.
 * User: durandcedric
 * Date: 25/09/16
 * Time: 11:43
 * 
 * Copyright (c) 2015-2017 Cédric DURAND (durandcedric@avitheque.net)
 * Dual licensed under the MIT (http://www.opensource.org/licenses/mit-license.php)
 * and GPL (http://www.opensource.org/licenses/gpl-license.php) licenses.
 */

global $sArticle;
// Initialisation du répertoire courant
define("ARTICLES_PATH", dirname(__FILE__) . '/articles');

// Récupération de l'instance du singleton InstanceStorage permettant de gérer les échanges avec le contrôleur
$oInstanceStorage = InstanceStorage::getInstance();

// Bouton [BAS DE PAGE]
ViewRender::addToMain("<span id=\"top\"><a class=\"page-top\" href=\"#bottom\" title=\"Bas de page...\">&#8595;</a></span>");

// Récupération de la variable par son nom
$aConnexion = $oInstanceStorage->getData('connexion');

// Présentation d'un article
$sArticle = "<h2>Documentation de développement</h2>
			<p>
				Le contenu de cet article a pour but de présenter un ensemble non exhaustif de fonctionnalités. Cette documentation est destinée au(x) développeur(s) en charge de maintenir cette application.
			</p>
			<p>
				<span class=\"strong\">Afin de profiter pleinement des exemples fournis, il vous est recommandé d'afficher votre navigateur en plein écran !</span>
			</p>";


// Initialisation d'un système d'onglets
$sArticle .= "<section class=\"tabs\">
				<ul>
					<li><a href=\"#tabs-architecture\">Architecture</a></li>
					<li><a href=\"#tabs-models\">Modèles</a></li>
					<li><a href=\"#tabs-controllers\">Contrôleurs</a></li>
					<li><a href=\"#tabs-views\">Vues</a></li>
					<li><a href=\"#tabs-formulaires\">Formulaires</a></li>
					<li><a href=\"#tabs-helpers\">Helpers</a></li>
					<li><a href=\"#tabs-styles\">Style CSS</a></li>
				</ul>";


//=================================================================================================
// ARCHITECTURE
//=================================================================================================
$sArticle .= "<div id=\"tabs-architecture\">";
// Présentation de l'architecture
require_once ARTICLES_PATH . "/architecture.php";
$sArticle .= "</div>";


//=================================================================================================
// MODÈLES
//=================================================================================================
$sArticle .= "<div id=\"tabs-models\">";
// Présentation de l'exploitation des modèles
require_once ARTICLES_PATH . "/models.php";
$sArticle .= "</div>";


//=================================================================================================
// CONTRÔLEURS
//=================================================================================================
$sArticle .= "<div id=\"tabs-controllers\">";
// Présentation de l'exploitation des contrôleurs
require_once ARTICLES_PATH . "/controllers.php";
$sArticle .= "</div>";


//=================================================================================================
// VUES
//=================================================================================================
$sArticle .= "<div id=\"tabs-views\">";
// Présentation de l'exploitation des vues
require_once ARTICLES_PATH . "/views.php";
$sArticle .= "</div>";


//=================================================================================================
// FORMULAIRES
//=================================================================================================
$sArticle .= "<div id=\"tabs-formulaires\">";
// Présentation de l'exploitation des formulaires
require_once ARTICLES_PATH . "/formulaires.php";
$sArticle .= "</div>";


//=================================================================================================
// HELPERS
//=================================================================================================

global $aListeItem;
global $aTitreItem;
$sArticle .= "<div id=\"tabs-helpers\">";
// Présentation de l'exploitation des formulaires
require_once ARTICLES_PATH . "/helpers.php";

//=================================================================================================
// @todo	ARBORESCENCEHELPER

// Présentation de l'exploitation de l'objet ArborescenceHelper
$sArticle .= "			<h3 class=\"item-title\">ArborescenceHelper</h3>
						<div class=\"item-content auto-height\" id=\"article-arborescence\">";
							// Ajout de l'article relatif à ArborescenceHelper
							require_once ARTICLES_PATH . "/ArborescenceHelper.php";
$sArticle .= "			</div>";

//=================================================================================================
// @todo	DATATABLEHELPER

// Présentation de l'exploitation de l'objet DatatableHelper
$sArticle .= "			<h3 class=\"item-title\">DatatableHelper</h3>
						<div class=\"item-content auto-height\" id=\"article-datatable\">";
							// Ajout de l'article relatif à DatatableHelper
							require_once ARTICLES_PATH . "/DatatableHelper.php";
$sArticle .= "			</div>";

//=================================================================================================
// @todo	GALLERYHELPER

// Présentation de l'exploitation de l'objet GalleryHelper
$sArticle .= "			<h3 class=\"item-title\">GalleryHelper</h3>
						<div class=\"item-content auto-height\" id=\"article-gallery\">";
							// Ajout de l'article relatif à GalleryHelper
							require_once ARTICLES_PATH . "/GalleryHelper.php";
$sArticle .= "			</div>";

//=================================================================================================
// @todo	PLANNINGHELPER

// Présentation de l'exploitation de l'objet PlanningHelper
$sArticle .= "			<h3 class=\"item-title\">PlanningHelper</h3>
						<div class=\"item-content auto-height\" id=\"article-planning\">";
							// Ajout de l'article relatif à PlanningHelper
							require_once ARTICLES_PATH . "/PlanningHelper.php";
$sArticle .= "			</div>";

//=================================================================================================
// @todo	TABLEHELPER

// Présentation de l'exploitation de l'objet TableHelper
$sArticle .= "			<h3 class=\"item-title\">TableHelper</h3>
						<div class=\"item-content auto-height\" id=\"article-table\">";
							// Ajout de l'article relatif à TableHelper
							require_once ARTICLES_PATH . "/TableHelper.php";
$sArticle .= "			</div>";

//=================================================================================================
// @todo	FIN DE L'ACCORDÉON

$sArticle .= "		</section>
				</div>
			</div>";


//=================================================================================================
// STYLE CSS
//=================================================================================================
$sArticle .= "<div id=\"tabs-styles\">";
// Présentation de l'exploitation des boutons
require_once ARTICLES_PATH . "/boutons.php";

// Séparateur vertical
$sArticle .= "<hr />";

// Présentation de l'exploitation des tableaux
require_once ARTICLES_PATH . "/tableaux.php";
$sArticle .= "</div>";

// Ajout du contenu au VIEW_MAIN
ViewRender::addToMain($sArticle);

// BOUTON [HAUT DE PAGE]
ViewRender::addToMain("<span id=\"bottom\"><a class=\"page-bottom\" href=\"#top\" title=\"Haut de page...\">&#8593;</a></span>");

//#################################################################################################
// VALIDATION DU FORMULAIRE
//#################################################################################################

// Ajout d'un bouton si l'utilisateur est Webmaster
$sWebmaster			= "";
if ($aConnexion['webmaster']) {
	$sWebmaster		= "<a href=\"/developpement/phpinfo\" class=\"width-150 button green tooltip\" title=\"Affichage de la configuration PHP\" target=\"_blank\">PHPInfo</a>
					<span class=\"margin-left-50 margin-right-50\">&nbsp;</span>";
}

// Ajout d'un bouton si le dépôt Git est actif
$sRepository		= "";
if (defined('GIT_ACTIVE') && (bool) GIT_ACTIVE) {
	$sRepository	= "<span class=\"margin-left-50 margin-right-50\">&nbsp;</span>
					<a href=\"" . GIT_REPOSITORY . "\" class=\"width-150 button green tooltip\" title=\"Accès au dépôt de l'application\" target=\"_blank\">Dépôt Git</a>";
}

// Présentation d'un bouton en bas, dans la barre des tâches de la page grâce au CSS
$sBottom = "<div class=\"group-button\">
				$sWebmaster
				<a href=\"" . JQUERY_PATH . "/" .JQUERY_UI_VERSION . "\" class=\"width-150 button green tooltip\" title=\"Accès à la documentation jQuery\" target=\"_blank\">Bibliothèque jQuery</a>
				$sRepository
			</div>";
ViewRender::addToFooter($sBottom);

// Ajout de la feuille de style CSS
ViewRender::linkFormulaireStyle('test.css');

// Rendu final de la vue
ViewRender::render();
