<?php
/**
 * @brief	Test
 *
 * Vue des infos PHP de développement de l'application.
 * User: durandcedric
 * Date: 25/09/16
 * Time: 11:43
 * 
 * Copyright (c) 2015-2017 Cédric DURAND (durandcedric@avitheque.net)
 * Dual licensed under the MIT (http://www.opensource.org/licenses/mit-license.php)
 * and GPL (http://www.opensource.org/licenses/gpl-license.php) licenses.
 */

// Affichage du résultat
print "<main class=\"padding-20\">";
phpinfo();
print "</main>";
