<?php
/**
 * @brief	Login
 *
 * Vue de connexion à l'application.
 * User: durandcedric
 * Date: 25/09/16
 * Time: 11:43
 * 
 * Copyright (c) 2015-2017 Cédric DURAND (durandcedric@avitheque.net)
 * Dual licensed under the MIT (http://www.opensource.org/licenses/mit-license.php)
 * and GPL (http://www.opensource.org/licenses/gpl-license.php) licenses.
 */

// Récupération de l'instance du singleton InstanceStorage permettant de gérer les échanges avec le contrôleur
$oInstanceStorage = InstanceStorage::getInstance();

//#################################################################################################
// INITIALISATION DES VALEURS PAR DÉFAUT
//#################################################################################################

// Données du formulaire
$aData		= $oInstanceStorage->getData('LOGIN');

//#################################################################################################
// PARAMÈTRAGE DU QUESTIONNAIRE
//#################################################################################################

// Initialisation des valeurs par défaut
$sLogin		= isset($aData['login'])	? DataHelper::get($aData, 'login')		: null;
$sPassword	= isset($aData['password'])	? DataHelper::get($aData, 'password')	: null;


//#################################################################################################
// INTERFACE DU QUESTIONNAIRE
//#################################################################################################

// Initialisation du formulaire
ViewRender::addToFormStart("<form action=\"#\" method=\"post\" name=\"login\">");

// Ajout d'un article
$sArticle	= "<article class=\"modal-25 padding-V-20 center\" id=\"article-login\">
				<h2>Connexion à un compte</h2>";

// Création du formulaire
$sArticle	.= "<table id=\"table-login\">
					<tr>
						<td>
							<label for=\"idLogin\" >Login : </label>
						</td>
						<td>
							</span><input type=\"text\" id=\"idLogin\" name=\"login\" value=\"" . $sLogin . "\" required/>
						</td>
					</tr>
					<tr>
						<td>
							<span><label for=\"idPassword\" >Mot de passe : </label>
						</td>
						<td>
							</span><input type=\"password\" id=\"idPassword\" name=\"password\" value=\"" . $sPassword . "\" required/>
						</td>
					</tr>
					<tr>
						<td colspan=2 class=\"center\">
							<button type=\"submit\" id=\"idConnexion\" class=\"button blue\" name=\"button\" value=\"connexion\" role=\"touche_C\">Connexion</button>
						</td>
					</tr>
				</table>";


//#################################################################################################
// VALIDATION DU FORMULAIRE
//#################################################################################################

// Finalisation du questionnaire
$sArticle .= "</article>";

// Ajout du contenu au VIEW_FORM_START pour l'exploitation du MODAL
ViewRender::addToFormStart($sArticle);

// Ajout de la feuille de style
ViewRender::linkFormulaireStyle("login.css");

// Ajout de la feuille de style
ViewRender::linkFormulaireScript("login.js");


//#################################################################################################
//	DEMO	DEMO	DEMO	DEMO	DEMO	DEMO	DEMO	DEMO	DEMO	DEMO	DEMO	DEMO
if (defined('MODE_DEMO') && (bool) MODE_DEMO) {
	// Liste des utilisateurs
	$aUserList	= array(
		// login			=> libellé
		'utilisateur'		=> "Utilisateur",
		'redacteur'			=> "Rédacteur",
		'valideur'			=> "Valideur",
		'administrateur'	=> "Administrateur",
	);
	// Mot de passe
	$sPassword				= 'demo';
	
	$sDialogue				= "Démonstration des fonctionnalités de l'application";
	
	$sMessage				= "Pour tester l'application, vous pouvez utiliser les comptes ";
	$nCount					= 1;
	foreach ($aUserList as $sLogin => $sLabel) {
		$nCount++;
		$sConcat			= " ";
		if ($nCount < count($aUserList)) {
			$sConcat		= ", ";
		} elseif ($nCount == count($aUserList)) {
			$sConcat		= " ou ";
		}
		
		// Initialisation du champ `title`
		$sTitle				= "Cliquez pour vous authentifier en tant que ''" . $sLabel . "''";
		
		// Ajout des informations de l'utilisateur
		$sMessage			.= sprintf('<span class="strong cyan italic pointer" title="%s">%s</span>%s', $sTitle, $sLogin, $sConcat);
	}
	
	// Finalisation du message
	$sMessage .= "avec le mot-de-passe <span class=\"strong green italic\">" . $sPassword . "</span> !";
	
	// Message de DEMO
	ViewRender::setMessageInfo($sDialogue, $sMessage);
	
	// Script permettant d'injecter directement les authentifications des comptes de DEMO
	$sJQuery = '$("span.pointer").click(function() {
					// Injection du login sélectionné
					$("input#idLogin").val($(this).text());
					// Injection du mot-de-passe de démonstration
					$("input#idPassword").val("' . $sPassword . '");
				});';
	
	// Compression du script avec JavaScriptPacker
	ViewRender::addToJQuery($sJQuery);
}
//	DEMO	DEMO	DEMO	DEMO	DEMO	DEMO	DEMO	DEMO	DEMO	DEMO	DEMO	DEMO
//#################################################################################################


// Rendu final de la vue
ViewRender::render();
