<?php
/**
 * @brief	Création
 *
 * Vue principale de création d'un formulaire QCM.
 *
 * @li Dans les tableaux, les clés de questions et de réponses commencent à la valeur [1].
 * User: durandcedric
 * Date: 25/09/16
 * Time: 11:43
 * 
 * Copyright (c) 2015-2017 Cédric DURAND (durandcedric@avitheque.net)
 * Dual licensed under the MIT (http://www.opensource.org/licenses/mit-license.php)
 * and GPL (http://www.opensource.org/licenses/gpl-license.php) licenses.
 */

//#################################################################################################
// INTERFACE DE CRÉATION DU QUESTIONNAIRE
//#################################################################################################

// Initialisation du formulaire
ViewRender::addToFormStart("<form action=\"#\" method=\"post\" name=\"creation\">");

// Construction du formulaire QCM
$oFormulaire = new FormulaireHelper(false, false, true, false);

// Création de l'entête du formulaire
$sArticle = "<h2>Création d'un nouveau QCM</h2>
			<p>
				Cette interface permet de réaliser un nouveau questionnaire QCM.
			</p>";
// Ajout du contenu au VIEW_MAIN
ViewRender::addToMain($sArticle);

// Zone du QCM injecté dans $_SESSION[VIEW_MAIN]
ViewRender::addToMain($oFormulaire->render());

//#################################################################################################
// VALIDATION DU FORMULAIRE
//#################################################################################################

// Création des boutons du formulaire
$oGroupButton = new GroupButtonHelper(false, false);
ViewRender::addToFooter($oGroupButton->render());

// Rendu final de la vue
ViewRender::render();
