<?php
/**
 * @brief	Épreuve QCM
 *
 * Vue du contrôle d'une épreuve QCM.
 * User: durandcedric
 * Date: 25/09/16
 * Time: 11:43
 *
 * Copyright (c) 2015-2017 Cédric DURAND (durandcedric@avitheque.net)
 * Dual licensed under the MIT (http://www.opensource.org/licenses/mit-license.php)
 * and GPL (http://www.opensource.org/licenses/gpl-license.php) licenses.
 */

//#################################################################################################
// INTERFACE DE CHARGEMENT DE L'ÉPREUVE QCM
//#################################################################################################

// Initialisation du formulaire
ViewRender::addToFormStart("<form action=\"#\" method=\"post\" name=\"controle\">");

// Construction du formulaire QCM
$oEpreuve = new EpreuveHelper(false, false, true, false);

// Création de l'entête du formulaire
$sArticle = "<h2>
				Épreuve QCM
			</h2>
			<p>
				Cette interface permet de passer une épreuve QCM.
			</p>";
// Ajout du contenu au VIEW_MAIN
ViewRender::addToMain($sArticle);

// Zone du QCM injecté dans $_SESSION[VIEW_MAIN]
ViewRender::addToMain($oEpreuve->render());


//#################################################################################################
// VALIDATION DU FORMULAIRE
//#################################################################################################

// Création des boutons du formulaire
$oGroupButton = new GroupButtonEpreuveHelper(true);
ViewRender::addToFooter($oGroupButton->render());

// Rendu final de la vue
ViewRender::render();
